### ISSUE TITLE
KMMO fails to check if image exists

### ISSUE THREAD

**Issue by hershpa** [rh-ecosystem-edge/kernel-module-management#43]
We have deployed KMMO commit e899b4cb4ae1665700e4fef77657c2867fe531ba on OCP 4.11. Seeing the following error in kmm-operator-controller-manager logs after deploying module CR. Pls advise, thanks! Can you share some examples or any documentation we can refer to while creating our module CR?

Our module CR looks like this at the moment:
```
> ---
> apiVersion: kmm.sigs.k8s.io/v1beta1
> kind: Module
> metadata:
>   name: intel-dgpu-kmmo
> spec:
>   moduleLoader:
>     container:
>       modprobe:
>         moduleName: intel-dgpu-kmmo
>       kernelMappings:
>         - literal: 4.18.0-372.19.1.el8_6.x86_64
>           containerImage: image-registry.openshift-image-registry.svc:5000/default/intel-dgpu-driver-container:4.18.0-372.19.1.el8_6.x86_64
>           build:
>             pull:
>               insecure: true
>             push:
>               insecure: true
>             secrets:
>               - name: image-registry-secret
>             dockerfile: |
>               FROM image-registry.openshift-image-registry.svc:5000/openshift/driver-toolkit:latest
>              .......
>   selector:
>     intel.feature.node.kubernetes.io/gpu: 'true'
```
**Error:**
``
E0914 21:50:02.207291 1 controller.go:326] "msg"="Reconciler error" "error"="failed to handle build for kernel version 4.18.0-372.19.1.el8_6.x86_64: failed to check image existence for kernel 4.18.0-372.19.1.el8_6.x86_64: could not check if the image is available: failed to get pull options for image image-registry.openshift-image-registry.svc:5000/default/intel-dgpu-driver-container:4.18.0-372.19.1.el8_6.x86_64: cannot get keychain from the registry auth getter: could not get the service account's pull secrets: serviceaccounts \"builder\" is forbidden: User \"system:serviceaccount:kmm-operator-system:kmm-operator-controller-manager\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"default\"" "controller"="module" "controllerGroup"="kmm.sigs.k8s.io" "controllerKind"="Module" "module"={"name":"intel-dgpu-kmmo","namespace":"default"} "name"="intel-dgpu-kmmo" "namespace"="default" "reconcileID"="0538c905-bc8a-4a47-80e6-e95ef8bbf2ec"``

**Comment by hershpa** [comment]
One more follow-up question, can we create the module CR in any namespace? Or does it have to be in a specific namespace for KMMO to work.

**Comment by qbarrand** [comment]
Hi @hershpa, this seems to be an oversight in the RBAC permissions of the operator following the implementation of the BuildConfig support. #47 should fix this issue.

> can we create the module CR in any namespace?

Yes, any namespace.

**Comment by hershpa** [comment]
Hi @qbarrand, thanks for the update and fix.

**Comment by hershpa** [comment]
Hi @qbarrand, still seeing the following issue after the fix: ``Get \"https://image-registry.openshift-image-registry.svc:5000/v2/\": x509: certificate signed by unknown authority"``

**Comment by hershpa** [comment]
Tested and seeing the above issue on 2 different OCP clusters.

**Comment by qbarrand** [comment]
@hershpa can this issue be closed?
